# Generated by Django 5.1.7 on 2025-03-13 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status_changed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
