# Generated by Django 5.1.7 on 2025-05-26 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_alter_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_treatment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='monitor.patient')),
            ],
            options={
                'verbose_name': 'Patientenhistorie Eintrag',
                'verbose_name_plural': 'Patientenhistorie Einträge',
                'ordering': ['-visit_date'],
            },
        ),
    ]
