# Generated by Django 5.1.7 on 2025-05-27 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_patient_last_treatment_notes_patienthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patienthistory',
            options={'ordering': ['-visit_date'], 'verbose_name': 'Historie Eintrag', 'verbose_name_plural': 'Historie Einträge'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_treatment_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Letzte Behandlungsnotizen'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('absend', 'Abwesend'), ('waiting', 'Wartend'), ('room1', 'Raum 1'), ('room2', 'Raum 2'), ('done', 'Fertig')], default='waiting', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status_changed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Status geändert am'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='notes',
            field=models.TextField(verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='monitor.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Besuchsdatum'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('first_name', 'last_name')},
        ),
    ]
