# Generated by Django migration
from django.db import migrations, models


def migrate_video_to_media(apps, schema_editor):
    """
    Migriert Video-Daten zum neuen Media-Modell
    """
    Video = apps.get_model('monitor', 'Video')
    Media = apps.get_model('monitor', 'Media')
    
    # Erstelle Media-Objekte aus bestehenden Video-Objekten
    for i, video in enumerate(Video.objects.all().order_by('id')):
        Media.objects.create(
            title=video.title,
            media_file=video.video_file,
            media_type=getattr(video, 'media_type', 'video'),  # Falls media_type bereits existiert
            display_duration=getattr(video, 'display_duration', 10),  # Falls display_duration bereits existiert
            order=i + 1,  # Setze Reihenfolge basierend auf der ursprünglichen ID-Reihenfolge
            created_at=video.created_at
        )


def reverse_migrate_media_to_video(apps, schema_editor):
    """
    Rückgängigmachen der Migration (falls notwendig)
    """
    Video = apps.get_model('monitor', 'Video')
    Media = apps.get_model('monitor', 'Media')
    
    # Erstelle Video-Objekte aus Media-Objekten
    for media in Media.objects.all():
        # Nur Videos zurück migrieren
        if media.media_type == 'video':
            Video.objects.create(
                title=media.title,
                video_file=media.media_file,
                created_at=media.created_at
            )


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_alter_patienthistory_options_and_more'),
    ]

    operations = [
        # Schritt 1: Füge neue Felder zum Video-Modell hinzu
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Reihenfolge'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='media/', verbose_name='Mediendatei'),
        ),
        
        # Schritt 2: Erstelle Media-Tabelle
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('media_file', models.FileField(upload_to='media/', verbose_name='Mediendatei')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('photo', 'Foto')], default='video', max_length=10, verbose_name='Medientyp')),
                ('display_duration', models.PositiveIntegerField(default=10, help_text='Anzeigedauer in Sekunden (nur für Fotos)', verbose_name='Anzeigedauer')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Medium',
                'verbose_name_plural': 'Medien',
                'ordering': ['order', 'id'],
            },
        ),
        
        # Schritt 3: Migriere Daten
        migrations.RunPython(
            migrate_video_to_media,
            reverse_migrate_media_to_video
        ),
        
        # Schritt 4: Lösche Video-Modell
        migrations.DeleteModel(
            name='Video',
        ),
    ]