# Generated by Django 5.1.7 on 2025-10-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_video_to_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Reihenfolge'),
        ),
    ]
