# Generated by Django 5.1.7 on 2025-10-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_alter_media_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Männlich'), ('female', 'Weiblich'), ('other', 'Divers')], default='female', max_length=10, verbose_name='Geschlecht'),
        ),
    ]
