# Generated by Django 5.1.7 on 2025-10-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Herr', 'Männlich'), ('Frau', 'Weiblich'), ('*', 'Divers')], default='Frau', max_length=10, verbose_name='Geschlecht'),
        ),
    ]
