# Generated by Django 5.1.7 on 2025-10-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='last_treatment_notes',
        ),
    ]
