# Generated by Django 5.1.7 on 2025-10-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_remove_patient_last_treatment_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientHistory',
        ),
    ]
