# Generated by Django 5.1.7 on 2025-10-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_delete_patienthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='display_duration',
            field=models.PositiveIntegerField(default=60, help_text='Anzeigedauer in Sekunden (nur für Fotos)', verbose_name='Anzeigedauer'),
        ),
    ]
